version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:4200"
            - "4200:4200"

